"""Add image column and role column

Revision ID: 20663e668e2e
Revises: 
Create Date: 2026-08-06 22:15:37.655367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20663e668e2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('image', sa.String(), nullable=True))
    op.drop_constraint(op.f('travels_duration_check'), 'travels', type_='check')
    op.drop_constraint(op.f('travels_price_check'), 'travels', type_='check')
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.drop_constraint(op.f('users_age_check'), 'users', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('users_age_check'), 'users', 'age >= 18')
    op.drop_column('users', 'role')
    op.create_check_constraint(op.f('travels_price_check'), 'travels', 'price > 0')
    op.create_check_constraint(op.f('travels_duration_check'), 'travels', 'duration > 0')
    op.drop_column('travels', 'image')
    # ### end Alembic commands ###
