"""Add (created) column in Bookings table

Revision ID: 8128215076ac
Revises: 05167f0fcf57
Create Date: 2026-09-13 20:17:11.420571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8128215076ac'
down_revision: Union[str, Sequence[str], None] = '05167f0fcf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'created')
    # ### end Alembic commands ###
